# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8613ebf9ba0769d1391980a33f429a6f75d30ef3aead2baafba8426bb15948e30002ef6f245b2a881fbf384186cdea8b07bef7f56b88d78d53b25dd70fd01ca2

test:
  secret_key_base: 68ef4ff9eaa1a2d9bdd803f02ba56d4f2d1e8ef6412c0fb2f39ae5c26b5b8d15e0c52567f583cadfbc35d0a1308a58cedb703178b8e0706526ff0e7942896c47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
